### ISSUE TITLE
pin memory与pytorch版本

### ISSUE THREAD

**Issue by Wakie01** [Lornatang/ESRGAN-PyTorch#17]
大佬，我在训练完一个epoch后，出现了下面问题，是不是pytorch版本没对应好呢？我的pytorch版本为1.7

```
Start train ESRGAN model.
Epoch: [1][ 1000/16696]	Time  0.370 ( 0.382)	Data  0.001 ( 0.001)	Pixel loss 0.037700 (0.052648)	Content loss 0.822794 (1.104305)	Adversarial loss 0.012794 (0.010927)	D(HR)  0.995 ( 0.988)	D(SR)  0.000 ( 0.006)	PSNR 22.59 (21.44)
Epoch: [1][ 2000/16696]	Time  0.379 ( 0.380)	Data  0.001 ( 0.001)	Pixel loss 0.029337 (0.041848)	Content loss 0.697089 (0.903808)	Adversarial loss 0.013856 (0.012345)	D(HR)  0.998 ( 0.991)	D(SR)  0.000 ( 0.003)	PSNR 24.02 (22.79)
Epoch: [1][ 3000/16696]	Time  0.370 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.033896 (0.037278)	Content loss 0.733463 (0.811156)	Adversarial loss 0.014888 (0.013205)	D(HR)  0.998 ( 0.993)	D(SR)  0.000 ( 0.002)	PSNR 23.61 (23.53)
Epoch: [1][ 4000/16696]	Time  0.380 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.027832 (0.034183)	Content loss 0.640709 (0.751329)	Adversarial loss 0.014274 (0.013682)	D(HR)  0.996 ( 0.994)	D(SR)  0.000 ( 0.002)	PSNR 26.16 (24.17)
Epoch: [1][ 5000/16696]	Time  0.380 ( 0.378)	Data  0.001 ( 0.001)	Pixel loss 0.022432 (0.032105)	Content loss 0.532851 (0.710133)	Adversarial loss 0.012825 (0.013611)	D(HR)  0.813 ( 0.972)	D(SR)  0.000 ( 0.002)	PSNR 27.34 (24.69)
Epoch: [1][ 6000/16696]	Time  0.379 ( 0.378)	Data  0.001 ( 0.001)	Pixel loss 0.024761 (0.030410)	Content loss 0.607785 (0.679033)	Adversarial loss 0.014104 (0.013516)	D(HR)  0.356 ( 0.945)	D(SR)  0.000 ( 0.002)	PSNR 27.39 (25.16)
Epoch: [1][ 7000/16696]	Time  0.380 ( 0.378)	Data  0.001 ( 0.001)	Pixel loss 0.019196 (0.029033)	Content loss 0.508872 (0.654894)	Adversarial loss 0.013619 (0.013771)	D(HR)  0.991 ( 0.935)	D(SR)  0.000 ( 0.002)	PSNR 28.68 (25.58)
Epoch: [1][ 8000/16696]	Time  0.380 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.018326 (0.027872)	Content loss 0.526340 (0.634764)	Adversarial loss 0.011635 (0.013911)	D(HR)  0.000 ( 0.847)	D(SR)  0.000 ( 0.002)	PSNR 28.88 (25.96)
Epoch: [1][ 9000/16696]	Time  0.384 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.019149 (0.026855)	Content loss 0.552133 (0.617711)	Adversarial loss 0.012062 (0.014202)	D(HR)  0.000 ( 0.791)	D(SR)  0.000 ( 0.002)	PSNR 29.79 (26.32)
Epoch: [1][10000/16696]	Time  0.379 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.015999 (0.025921)	Content loss 0.565542 (0.602837)	Adversarial loss 0.015624 (0.014473)	D(HR)  0.014 ( 0.726)	D(SR)  0.000 ( 0.001)	PSNR 30.17 (26.66)
Epoch: [1][11000/16696]	Time  0.380 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.018763 (0.025180)	Content loss 0.423601 (0.590442)	Adversarial loss 0.019162 (0.014849)	D(HR)  0.000 ( 0.669)	D(SR)  0.000 ( 0.001)	PSNR 29.96 (26.96)
Epoch: [1][12000/16696]	Time  0.379 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.012981 (0.024501)	Content loss 0.429494 (0.579708)	Adversarial loss 0.021525 (0.015203)	D(HR)  0.006 ( 0.632)	D(SR)  0.000 ( 0.001)	PSNR 31.68 (27.22)
Epoch: [1][13000/16696]	Time  0.380 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.021055 (0.023893)	Content loss 0.483494 (0.569777)	Adversarial loss 0.021465 (0.015379)	D(HR)  0.000 ( 0.597)	D(SR)  0.000 ( 0.001)	PSNR 29.54 (27.47)
Epoch: [1][14000/16696]	Time  0.380 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.017674 (0.023372)	Content loss 0.444889 (0.561240)	Adversarial loss 0.017812 (0.015906)	D(HR)  0.000 ( 0.563)	D(SR)  0.000 ( 0.001)	PSNR 30.26 (27.69)
Epoch: [1][15000/16696]	Time  0.380 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.017920 (0.022861)	Content loss 0.408098 (0.553281)	Adversarial loss 0.020351 (0.016176)	D(HR)  0.002 ( 0.536)	D(SR)  0.000 ( 0.001)	PSNR 30.25 (27.92)
Epoch: [1][16000/16696]	Time  0.379 ( 0.379)	Data  0.001 ( 0.001)	Pixel loss 0.013671 (0.022394)	Content loss 0.497734 (0.545935)	Adversarial loss 0.016718 (0.016400)	D(HR)  0.000 ( 0.510)	D(SR)  0.000 ( 0.002)	PSNR 31.51 (28.12)
Valid: [   0/3843]	Time  0.408 ( 0.408)	PSNR 37.65 (37.65)
Valid: [1000/3843]	Time  0.080 ( 0.081)	PSNR 34.63 (36.69)
Valid: [2000/3843]	Time  0.081 ( 0.081)	PSNR 37.63 (36.68)
Valid: [3000/3843]	Time  0.097 ( 0.082)	PSNR 37.98 (36.69)
* PSNR: 36.67.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/myuser/.conda/envs/esrgan_lornatang/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/myuser/.conda/envs/esrgan_lornatang/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/myuser/.conda/envs/esrgan_lornatang/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)

Traceback (most recent call last):
  File "train_esrgan.py", line 390, in <module>
    main()
  File "train_esrgan.py", line 86, in main
    writer)
  File "train_esrgan.py", line 216, in train
    for index, (lr, hr) in enumerate(train_dataloader):
  File "/home/myuser/.conda/envs/esrgan_lornatang/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 349, in __iter__
    self._iterator._reset(self)
  File "/home/myuser/.conda/envs/esrgan_lornatang/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 852, in _reset
    data = self._get_data()
  File "/home/myuser/.conda/envs/esrgan_lornatang/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
```

**Comment by Lornatang** [comment]
persistent_workers=False？

**Comment by Lornatang** [comment]
我的PyTorch环境为10.2

**Comment by Wakie01** [comment]
我设置pin_memory=False后可以了，persistent_workers还是True

**Comment by Lornatang** [comment]
好奇怪的问题，还没遇到过，等下再测试一下代码

**Comment by Lornatang** [comment]
@Wakie01 测试通过了，没有发现问题

**Comment by Wakie01** [comment]
> 我设置pin_memory=False后可以了，persistent_workers还是True

没事，我就设置pin_memory=False，也行了，我感觉就是pytorch版本没对应你的，谢谢你！！
